### ISSUE TITLE
Regarding Table 2 in the paper, I have a question.

### ISSUE THREAD

**Issue by yuanJunjun001** [Skyd-Semantic/DRGO-SemCom#3]
Hello! It seems that the Loss values presented in Table 2 of this document need to be divided by 256 after obtaining the MSE for each image. Although the code has already computed the mean based on the batch size, there's an additional division by 256.Could you please clarify whether these Loss values represent the reconstruction rate or the distortion rate as mentioned in the document? Your assistance is appreciated.
您好！我发现本文表2得出的Loss值都要通过每张图的MSE再除以256得出。代码中已经根据batch_size求了均值，我想问下为啥还要除以个256。还有这个Loss值是文中说的重建率还是失真率？麻烦您了，希望您能解答。

**Comment by skydvn** [comment]
The distortion can be measured as squared error distortion (https://en.wikipedia.org/wiki/Rate%E2%80%93distortion_theory), thus, the MSE of the reconstruction loss can be considered as the distortion rate without loss of generality :D 
About the additional division by 256, i thought you mean the implementation section. Its for the results saving, as the code want to simulate the compression ratio, which is measured by original data size / compressed data size (latent embeddings size).
